### ISSUE TITLE
About downloading

### ISSUE THREAD

**Issue by Philae994** [jaditi930/Instagram-Posts-Downloader#1]
When I use download all posts, the download will automatically stop after a part is downloaded, and the download will not continue if I start it again.

**Comment by ghost** [comment]
Same here. It was working fine for me on Friday, but then at some point now it isn't working at all. Just keeps saying "Sorry could not download the file, Please check username/url try back later.

**Comment by jaditi930** [comment]
@Philae994 The issue seems to be with the instaloader module and not the code. I will look into it and see if something can be done. Thanks for pointing that out.

**Comment by jaditi930** [comment]
@neato82 Can you tell me specifically what you were trying to download? One thing to note here is that you cannot download posts or videos from private profiles.

**Comment by ghost** [comment]
Hey no worries.
Only sourcing public profiles.
Just trying to do full profile downloads mostly.
Thanks!

**Comment by Philae994** [comment]
After replacing the network proxy, the problem seems to have been resolved更换网络代理后，问题似乎已解决

**Comment by Philae994** [comment]
After replacing the network proxy, the problem seems to have been resolved
